account/urls.py
from django.urls import path
from . import views





urlpatterns = [ 
    
    path('sign-in/',views.loginpage,name="login"),
    path('sign-up/',views.registerpage,name="register"),
    path('sign-out/',views.logout_view,name="logout"),
    path('activate/<uidb64>/<token>/', views.account_activate_view, name='activate'),
]

antecfinance/urls.py
from django.contrib import admin
from django.urls import path,include
from  django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import  views as auth_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('', include('users.urls')),
    path('', include('superusers.urls')),

     path('password-reset/', auth_view.PasswordResetView.as_view(template_name='auth/password-reset.html'), name='password-reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='auth/password-reset-done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_view.PasswordResetConfirmView.as_view(template_name='auth/password-reset-confirm.html'), name='password_reset_confirm'),
    path('password-reset/complete/', auth_view.PasswordResetCompleteView.as_view(template_name='auth/password-reset-complete.html'), name='password_reset_complete'),

]

home/urls.py
from django.urls import path
from . import views





urlpatterns = [ 
    path('',views.homepage,name="homepage"),
    path('about/',views.aboutpage,name="aboutpage"),
    path('contact/',views.contactpage,name="contactpage"),
    path('pricing/',views.pricingpage,name="pricingpage"),
    path('services/',views.servicespage,name="servicespage"),
]

users/urls.py
from django.urls import path
from . import views





urlpatterns = [ 
    
    path('wallet/',views.dashbaord_view,name="dashboard"),
    path('withdraw-funds/',views.withdrawal_view,name="withdraw"),
    path('fund-account/',views.deposit_view,name="deposit"),
    path('my-account-settings/',views.settings_view,name="settings"),
    path('update-password/',views.change_password_view,name="change_password"),
    path('account-logs/',views.history_view,name="history"),
    path('notifications/',views.notification_view,name="notifications"),
    path('create-investment/',views.create_investment_view,name="create_investment"),
    path('credit-user-investment/', views.end_user_investment_view, name="end_user_investment_view"),
    path('referrals/',views.referral_view,name="referrals"),

    
]

account/models.py
from django.db import models 
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.conf import settings 

import random
import json
import string
#from uuid import uuid4






class Account(AbstractUser):
    email       = models.EmailField(verbose_name='email', max_length=60, unique=True )
    zipcode    = models.CharField(max_length=30,blank=True,null=True)
    country    = models.CharField(max_length=100,blank=True,null=True)
    
    address    = models.CharField(max_length=100,blank=True,null=True)
    gender    = models.CharField(max_length=100,blank=True,null=True)
    state    = models.CharField(max_length=100,blank=True,null=True)
    city    = models.CharField(max_length=100,blank=True,null=True)

    date_of_birth = models.CharField(max_length=100,blank=True,null=True)

    #profile_image = models.ImageField(blank=True, null=True, upload_to='uploads')
    phone = models.CharField(max_length=30, blank=True,null=True,unique=True)
    balance = models.IntegerField(default=0, blank=True,null=True)
    deposite_balance = models.IntegerField(default=0, blank=True,null=True)
    total_amount_invested = models.IntegerField(default=0, blank=True,null=True)
    total_investement_count = models.IntegerField(default=0, blank=True,null=True)
    withdraw_total = models.IntegerField(default=0, blank=True,null=True) 
    is_email_verifield = models.BooleanField(default=False)
    bonus = models.IntegerField(default=0,blank=True,null=True)
    refferal = models.IntegerField(default=0,blank=True,null=True)



    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']



    def __str__(self):
        return self.email






class RefferalProfile(models.Model):
    user = models.OneToOneField(Account, on_delete = models.CASCADE)
    recommended_by = models.ForeignKey(Account,related_name='recom_user', on_delete=models.CASCADE,null=True, blank=True)
    #recomended_users = models.ManyToManyField(Account, related_name='fri',blank=True)
    date = models.DateTimeField(auto_now_add=True)
    bonus = models.IntegerField(default=0,blank=True,null=True)



    def recom_profies(self):
        qs = RefferalProfile.objects.all()
        my_rec = []
        for profile in qs:
            if profile.recommended_by == self.user:
                my_rec.append(profile)
        return my_rec



    def __str__(self):
        return self.user.username

account/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.contrib.auth  import login,authenticate,logout
from .models import Account





class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    firstname = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'Firstname'
            }
        ),
        label = 'Firstname',
        required=True
    )
    lastname = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'Lastname'
            }
        ),
        label = 'Lastname',
        required=True
    )
    email = forms.EmailField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'email',
                'class': 'form-control',
                'placeholder':"Email"
            }
        ),
        label = 'Email',
        required=True
    )
    phone = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'tel',
                'class': 'form-control',
                'placeholder':'PHONE'
            }
        ),
        label = "PHONE",
         required=True
    )
    password1 = forms.CharField( max_length=30, min_length=6,label='Password', widget=forms.PasswordInput(attrs={'placeholder': "PASSWORD", 'class': 'form-control',}))
    #password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': "CONFIRM PASSWORD", 'class': 'form-control',}))

    class Meta:
        model = Account
        fields = ('firstname','lastname',"username",'email','phone','password1')


    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user




class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Account
        fields = ('email', 'password', 'date_of_birth', 'is_active', 'is_staff')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]









class UserActivateForm(forms.ModelForm):

    country = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'Country'
            }
        ),
        label = '',
        required=True
    )
    city = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'City'
            }
        ),
        label = '',
        required=True
    )
    state = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'ZIPCODE'
            }
        ),
        label = '',
        required=True
    )
    address = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'ADDRESS'
            }
        ),
        label = '',
        required=True
    )
 
    zipcode = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'zipcode'
            }
        ),
        label = '',
        required=True
    )
    gender = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                "placeholder":'Gender'
            }
        ),
        label = '',
        required=True
    )

 


    class Meta:
        model = Account
        fields = ['country','city','state','address','zipcode','gender']




class LoginForm(forms.ModelForm):
    email = forms.EmailField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'type': 'email',
                'class': 'form-control',
                "placeholder":'EMAIL'
            }
        ),
        label = 'Email',
        required=True
    )
    password = forms.CharField( max_length=30, min_length=4,label='Password', widget=forms.PasswordInput(attrs={'placeholder': "PASSWORD", 'class': 'form-control',}))

    class Meta:
        model = Account
        fields = ['email','password']

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password =  self.cleaned_data['password']
            if not authenticate(email=email,password=password):
                raise forms.ValidationError('Invalid Credentials Note : Make Sure Your Email Address Is Verified')


account/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import  messages
from django.http import JsonResponse
from django.contrib.auth  import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_text
from django.urls import reverse_lazy
from django.core.mail import EmailMessage, send_mail
from django.template import Context
from django.template.loader import render_to_string, get_template






from .models import Account,RefferalProfile
from .forms import UserCreationForm,LoginForm



EMAIL_ADMIN = "worldcryptocurrencies01@gmail.com"

def calculate_perc():
    return 100

def loginpage(request):
    return render(request,'auth/login.html')



def registerpage(request):
    if request.POST:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = '@'+str(request.POST.get('username'))
            instance = form.save(commit=False)
            instance.username = username
            instance.firstname = str(request.POST.get('firstname'))
            instance.lastname = str(request.POST.get('lastname'))
            instance.is_active = False
            instance.save()
            

            if request.POST.get('refferd_by'):
                refferd_by_id = int(request.POST.get('refferd_by'))
                print(refferd_by_id)
                try:
                    refferd_by_user = Account.objects.get(pk=refferd_by_id)
                    new_user_ref =  RefferalProfile.objects.create(user=instance)
                    new_user_ref.recommended_by = refferd_by_user
                    new_user_ref.save()
                    old_user_ref = RefferalProfile.objects.get(user =refferd_by_user)
                    old_user_ref.user.refferal += 1
                    old_user_ref.user.bonus += calculate_perc()
                    old_user_ref.user.balance += calculate_perc()
                    old_user_ref.save()
                    old_user_ref.user.save()
                except:
                    messages.info(request, f'Something went Wrong')
                    return redirect('register')
            else:
                RefferalProfile.objects.create(user=instance)






            current_site = get_current_site(request)
            subject = '[Antecfinance]Confirm Your Email Address'
            context = {
                'user': instance,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(instance.pk)),
                'token': default_token_generator.make_token(instance),
                }
            message = get_template("auth/account_activation_email.html").render(context)
            mail = EmailMessage(
                subject=subject,
                body=message,
                from_email=EMAIL_ADMIN,
                to=[instance.email],
                reply_to=[EMAIL_ADMIN],
            )
            mail.content_subtype = "html"
            mail.send(fail_silently=True)
            
            messages.success(request, ('Please check your mail box for confirmation email'))
            return redirect("register")
    else:
        form = UserCreationForm()
    if request.GET.get('ref-code'):
        refferd_by = request.GET.get('ref-code')
        return render(request, 'auth/registerii.html',{"form":form , "refferd_by" : refferd_by})
    else:
        return render(request, 'auth/registerii.html',{"form":form})














def account_activate_view(request, uidb64, token, *args, **kwargs):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.is_email_verifield = True
        user.save()
        login(request, user)
        messages.success(request, ('Please Complete Your Account Setup'))
        return redirect('settings')
    else:
        messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
        return redirect('register')




def loginpage(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    destination = get_redirect_if_exists(request) 
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            destination = request.POST.get('destination')
            user = authenticate(email=email, password=password)
            if user:
                login(request,user)
                if destination:
                    return redirect(destination)
                else:
                    return redirect("dashboard")
    else:
        form = LoginForm()
    #messages.success(request, ('Please Complete Your Account Setup'))
    return render(request, 'auth/loginii.html',{"form":form,"destination":destination})



def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.GET.get("next"):
            redirect = str(request.GET.get("next"))
    return redirect


def logout_view(request):
    logout(request)
    return redirect('login')




templates/users/change_password.html
{% extends "layout/users.html" %}{% load crispy_forms_tags %} {% block title %} Change Password {% endblock title %} {% block stylesheet %} {% endblock stylesheet %} {% block content %}
<header>
    <!-- TopBar -->
    <nav class="navbar navbar-expand   topbar mb-4 static-top">
        <a href="{% url 'dashboard' %}" id="sidebarToggleTop2" class=" rounded-circle mr-3 text-white ">
            <i class="fas fa-arrow-left"></i>
            <span>Settings</span>
        </a>
        <ul class="navbar-nav ml-auto">

            <li class="nav-item    mx-1">
                <a class="nav-link  " href="{% url 'notifications' %}" id="alertsDropdown">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger badge-counter">1</span>
                </a>

            </li>


            <div class="topbar-divider d-none d-sm-block"></div>
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="img-profile rounded-circle" src="/static/images/avatar.png" style="max-width: 60px">
                    <span class="ml-2 d-none d-lg-inline text-white small">{{user.username}}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">

                    <a class="dropdown-item" href="/my-account-settings/?tab=Update Profile">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 "></i> Settings
                    </a>
                    <a class="dropdown-item" href="{% url 'history' %}">
                        <i class="fas fa-list fa-sm fa-fw mr-2 "></i> Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 "></i> Logout
                    </a>
                </div>
            </li>
        </ul>
    </nav>
    <!-- Topbar -->
</header>

<div class="content" style="min-height: 87vh;">
    <div class="container">
        <div class="col-xl-12">
            <div class="row justify-content-center">
                <div class="col-7">
                    <div class="depo-card breadcrum">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Settings </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="space-top deposite"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-4 col-lg-4">

                    <p><a href="{% url 'settings' %}" class="btn btn-primary btn-block"><i class="fa fa-user"></i> Account settings  </a></p>
                    <p><a href="{% url 'change_password' %}" class="btn btn-primary btn-block "><i class="fa fa-cog"></i> Security</a></p>



                </div>
                <div class="col-xl-8 col-lg-8">

                    <div class="tab-content" id="myTabContent">

                        <div class="tab-pane show active   fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            <form action=" " method="post" id="profile-form">
                                {% csrf_token %} {{ p_form|crispy }}
                                <div class="form-group">

                                    <input type="submit" name="submit" id="" class="btn btn-primary btn-block" value="Change Password">
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>





{% endblock content %} {% block javascripts %} {% endblock javascripts %}

templates/users/settings.html
{% extends "layout/users.html" %}{% load crispy_forms_tags %} {% block title %} Account Settings {% endblock title %} {% block stylesheet %} {% endblock stylesheet %} {% block content %}
<header>
    <!-- TopBar -->
    <nav class="navbar navbar-expand   topbar mb-4 static-top">
        <a href="{% url 'dashboard' %}" id="sidebarToggleTop2" class=" rounded-circle mr-3 text-white ">
            <i class="fas fa-arrow-left"></i>
            <span>Settings</span>
        </a>
        <ul class="navbar-nav ml-auto">

            <li class="nav-item    mx-1">
                <a class="nav-link  " href="{% url 'notifications' %}" id="alertsDropdown">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger badge-counter">{{user_notify_count}}</span>
                </a>

            </li>


            <div class="topbar-divider d-none d-sm-block"></div>
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="img-profile rounded-circle" src="/static/images/avatar.png" style="max-width: 60px">
                    <span class="ml-2 d-none d-lg-inline text-white small">{{user.username}}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">

                    <a class="dropdown-item" href="/my-account-settings/?tab=Update Profile">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 "></i> Settings
                    </a>
                    <a class="dropdown-item" href="{% url 'history' %}">
                        <i class="fas fa-list fa-sm fa-fw mr-2 "></i> Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 "></i> Logout
                    </a>
                </div>
            </li>
        </ul>
    </nav>
    <!-- Topbar -->
</header>

<div class="content" style="min-height: 87vh;">
    <div class="container">
        <div class="col-xl-12">
            <div class="row justify-content-center">
                <div class="col-7">
                    <div class="depo-card breadcrum">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Settings </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="space-top deposite"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12">
                    <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active  " href="{% url 'settings' %}" aria-controls="home" aria-selected="true">Profile Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary ml-2 mb-2" href="{% url 'change_password' %}" aria-controls="profile" aria-selected="false">Security</a>
                        </li>

                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade  show active  " id="home" role="tabpanel" aria-labelledby="home-tab">
                            <div class="form mt-3 mb-3">
                                <form action="" method="post" class="mt-5" id="profileform">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            {{ u_form.country|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-md-4">
                                            {{ u_form.city|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-md-4">
                                            {{ u_form.state|as_crispy_field }}
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        {{ u_form.address|as_crispy_field }}
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            {{ u_form.zipcode|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-md-4">
                                            {{ u_form.date_of_birth|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-md-4">
                                            {{ u_form.gender|as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        {{ u_form.phone|as_crispy_field }}
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" name="submit" id="submit_btn" class="btn btn-primary btn-block" value="Update Profile">
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>





{% endblock content %} {% block javascripts %}
<script type="text/javascript">
    $('#id_date_of_birth').datepicker({
        startView: 2,
        format: 'yyyy/mm/dd',
        autoclose: true,
        todayHighlight: true,
        todayBtn: 'linked',
    });
</script>

{% endblock javascripts %}